comman = [
    "Try not. Do or do not. There is no try. —Yoda, Star Wars Episode V: The Empire Strikes Back",
    "Your eyes can deceive you; don’t trust them. —Obi-Wan Kenobi, Star Wars Episode IV: A New Hope",
    "Luminous beings we are, not this crude matter. —Yoda, The Empire Strikes Back",
    "Who’s the more foolish: the fool or the fool who follows him? —Obi-Wan Kenobi, A New Hope",
    "Your focus determines your reality. —Qui-Gon Jinn, Star Wars Episode I: The Phantom Menace",
    "No longer certain that one ever does win a war, I am. —Yoda, The Clone Wars",
    "In a dark place we find ourselves and a little more knowledge lights our way. —Yoda, Star Wars Episode III: Revenge Of The Sith",
    "Sometimes we must let go of our pride and do what is requested of us. —Anakin Skywalker, Star Wars Episode II: Attack Of The Clones",
    "We’ll always be with you. No one’s ever really gone. A thousand generations live in you now. —Luke Skywalker, Star Wars Episode IX: The Rise of Skywalker",
    "Difficult to see; always in motion is the future. —Yoda, The Empire Strikes Back",
    "Many of the truths that we cling to depend on our viewpoint. —Obi-Wan Kenobi, Star Wars Episode VI: Return Of The Jedi",
    "Train yourself to let go of everything you fear to lose. —Yoda,Revenge Of The Sith",
    "I like firsts. Good or bad, they’re always memorable. —Ahsoka Tano, The Mandalorian",
    "Great, kid, don’t get cocky. —Han Solo, A New Hope",
    "Congratulations. You are being rescued. —K-2SO, Rogue One: A Star Wars Story",
    "Sorry lady. I don’t understand frog. —Din The Mandalorian",
    "Insolence? We are pirates. We don’t even know what that means. —Hondo Ohnaka, The Clone Wars",
    "I am not a committee. —Princess Leia, The Empire Strikes Back",
    "I’m a Mandalorian. Weapons are part of my religion. —Mando, The Mandalorian",
    "Come on, baby! Do the magic hand thing. —Greef Karga, The Mandalorian",
    "Be careful not to choke on your aspirations, director. —Darth Vader, Rogue One",
    "Once you start down the dark path, forever will it dominate your destiny. —Yoda, The Empire Strikes Back",
    "Fear leads to anger, anger leads to hate, hate leads to suffering. —Yoda, The Phantom Menace",
  "I’ve seen what such feelings can do to a fully trained Jedi Knight. To the best of us. —Ahsoka Tano, The Mandalorian"
]
